<?php
return [
    'files' => env('SITE_FILES','files'),
    'VIVVO_ANALYTICS_TRACKER_ID' => true,
    "lang" => array(
        'LNG_SEARCH_ALL' => 'إبحث في كل الأخبار',
        'LNG_SEARCH_ADVANCED' => 'بحث متقدم',
        'LNG_SEARCH_CAT' => 'أقسام البحث',
        'LNG_SEARCH_ALL_CATEGORIES' => 'بحث في كل الأقسام',
        'LNG_SEARCH_KEYWORD' => 'بحث بواسطة كلمات مفتاحية',
        'LNG_SEARCH_USER' => 'بحث بواسطة اسم المستخدم',
        'LNG_SEARCH_USER_NAME' => 'حسب الاسم',
        'LNG_SEARCH_USERGROUP' => 'المجموعات',
        'LNG_SEARCH_OPTION' => 'خيارات البحث',
        'LNG_SEARCH_POST' => 'البحث عن الردود من',
        'LNG_SEARCH_OPTION_ANY_DATE' => 'أي تاريخ',
        'LNG_SEARCH_OPTION_YESTRDAY' => 'الأمس',
        'LNG_SEARCH_OPTION_A_WEEK_AGO' => 'الأسبوع الماضي',
        'LNG_SEARCH_OPTION_2_WEEKS_AGO' => 'منذ أسبوعين',
        'LNG_SEARCH_OPTION_A_MONTH_AGO' => 'الشهر الماضي',
        'LNG_SEARCH_OPTION_3_MONTHS_AGO' => 'منذ ثلاثة أشهر',
        'LNG_SEARCH_OPTION_6_MONTHS_AGO' => 'منذ ستة أشهر',
        'LNG_SEARCH_OPTION_A_YEAR_AGO' => 'منذ سنة',
        'LNG_SEARCH_SITE' => 'بحث في الموقع',
        'LNG_SEARCH_SORT' => 'ترتيب النتائج حسب',
        'LNG_SEARCH_STATUS' => 'بحث حسب الوضع',
        'LNG_SEARCH_REFINE' => 'الرجاء تحديد نوع البحث',
        'LNG_SEARCH_NARROW' => 'لديك أكثر من 100 نتيجة للبحث. يرجى تضييق نطاق البحث.',

        'LNG_SEARCH_RESULT' => 'وجد',
        'LNG_SEARCH_RESULTS' => 'نتيجة البحث',
        'LNG_SEARCH_NO_RESULT' => 'لا يوجد نتائج لإستفسارك.',
        'LNG_SEARCH_NO_RESULT1' => 'لا يوجد أي نتائج تحتوي على',
        'LNG_SEARCH_NO_RESULT2' => ' إنتهى. من فضلك, أعد البحث مرة أخرى.',

        'LNG_SEARCH_FORM_AUTHOR' => 'المؤلف',
        'LNG_SEARCH_FORM_AND_OLDER' => 'وأقدم',
        'LNG_SEARCH_FORM_CATEGORIES' => 'بحث في الأقسام (اضعط ctrl لتعدد الخيارات)',
        'LNG_SEARCH_FORM_EXACT_NAME' => 'مطابق للاسم',
        'LNG_SEARCH_FORM_KEYWORD' => 'الكلمات المفتاحية',
        'LNG_SEARCH_FORM_POST' => 'إيجاد المقالات من',
        'LNG_SEARCH_FORM_TITLES_ONLY' => 'العناوين فقط',

        'LNG_ARTICLE_POSTED_ON' => 'على',

        'LNG_SELECT_DAY' => 'اختر اليوم',
        'LNG_SELECT_MONTH' => 'اختر الشهر',
        'LNG_SELECT_YEAR' => 'اختر السنة',

        'LNG_SORT_BY' => 'رتب حسب',
        'LNG_SORT_AUTHOR' => 'المؤلف',
        'LNG_SORT_DATE' => 'التاريخ',
        'LNG_SORT_TITLE' => 'الموضوع',

        'LNG_LOG_IN' => 'تسجيل دخول',
        'LNG_LOG_OUT' => 'تسجيل خروج',
        'LNG_NOT_LOGGED' => 'يجب أن تكون مسجلا لإضافة التعليقات',
        'LNG_NO_LOGGED_NO_COMMENT' => 'يجب أن تكون مسجلا لإضافة التعليقات',

        'LNG_COMMENT' => 'التعليق',
        'LNG_COMMENTS' => 'عدد التعليقات',
        'LNG_COMMENT_POST' => 'أضف تعليقك',
        'LNG_COMMENT_POSTED' => 'تعليق',
        'LNG_ARTICLE_COMMENTS_POSTED' => 'مرسل من',
        'LNG_ARTICLE_COMMENTS_POSTED_ON' => 'في',
        'LNG_COMMENT_RSS' => 'الإشتراك في تعليقات نظام RSS',
        'LNG_LATEST_COMMENTS' => 'آخر التعليقات',
        'LNG_NO_COMMENT_POSTED' => ' - لا يوجد تعليقات مرسلة',
        'LNG_NUM_COMMENT_POSTED' => ' تعليقات مرسلة',
        'LNG_COMMENTS_REPORT_INAPPROPRIATE' => 'تقرير كغير لائق',
        'LNG_COMMENTS_THUMB_UP' => 'مقبول',
        'LNG_COMMENTS_THUMB_DOWN' => 'مرفوض',
        'LNG_REPORT_COMMENT_SENT' => 'تعليقات غير لائقة.',
        'LNG_REPORT_COMMENT_FAILD' => 'البريد الإلكتروني لا يمكن إرساله.',
        'LNG_REPORT_COMMENT_MAIL_SUBJECT' => 'البريد المعلن عنه من <WEBSITE_TITLE>',
        'LNG_REPORT_COMMENT_IP_ADDRESS_AUTHOR_COMMENT' => 'عنوان الـ IP للشخص الذي أرسل التعليق',
        'LNG_REPORT_COMMENT_REPORTED_COMMENT_INFO' => 'العضو الذي أعلم عن التعليق',
        'LNG_REPORT_COMMENT_MESSAGE_1' => 'الرجاء الرد بشكل ملائم.',
        'LNG_REPORT_COMMENT_MESSAGE_2' => 'هذا التعليق جزء من المقال',
        'LNG_COMMENT_REPLY' => 'رد',
        'LNG_COMMENT_REPLYING_TO' => 'أنت/ تكتب رد إلى',

        'LNG_COMMENTS_BBCODE_BOLD' => 'عريض',
        'LNG_COMMENTS_BBCODE_ITALIC' => 'مائل',
        'LNG_COMMENTS_BBCODE_UNDERLINE' => 'تحته خط',
        'LNG_COMMENTS_BBCODE_QUOTE' => 'إقتباس',
        'LNG_COMMENTS_BBCODE_INSERT_LINK' => 'أدخل رابط',
        'LNG_COMMENTS_BBCODE_LINK_URL' => 'الرابط',
        'LNG_COMMENTS_BBCODE_LINK_TEXT' => 'النص',

        'LNG_CANT_POSTED_COMMENTS' => 'فقط الأعضاء المسجلين!',
        'LNG_CANT_POSTED_COMMENTS_BAD_WORDS' => 'لا يمكنك نشر هذا التعليق لأنك إستخدمت العبارة التالية:',

        'LNG_ADD_COMMENTS' => 'نص التعليق',
        'LNG_ADD_COMMENTS_AUTHOR' => 'اسمك',
        'LNG_ADD_COMMENTS_WWW' => 'موقعك',
        'LNG_ADD_COMMENT_CAPTCHA' => 'من فضلك أدخل الكود الذي تراه في الصورة:',
        'LNG_ADD_COMMENTS_MAIL' => 'بريدك الإلكتروني',
        'LNG_ADD_COMMENTS_WAITING' => 'تم حفظ تعليقك وسوف يكون مرئي بعد الموافقة عليه.',

        'LNG_ADDED_COMMENT1' => 'لقد أضيف تعليقك بنجاح.',
        'LNG_ADDED_COMMENT2' => 'عودة إلى صفحة المقال',
        'LNG_ADDED_COMMENT3' => 'لقد أضيف تعليقك وينتظر الموافقة عليه.',

        'LNG_NO_ARTICLES' => 'لا يوجد أي موضوع في القسم المحدد.',
        'LNG_NO_CATEGORY_ARTICLES' => 'لا يوجد أي مواضيع في هذا القسم',
        'LNG_ARTICLES_PER_PAGE' => 'المقالات بكل صفحة',
        'LNG_EMAIL__ARTICLE' => 'أرسل هذا المقال',

        'LNG_POPULAR_TAGS' => 'أكثر الكلمات الدلالية بحثاً',
        'LNG_ALL_TAGS' => 'عرض كل الكلمات الدليلة',
        'LNG_ARTICLE_TAGS' => 'الكلمات الدلالية',
        'LNG_ARTICLE_TAGGED_AS' => 'الكلمات الدلالية',
        'LNG_NO_TAGS_FOR_ARTICLE' => 'لا يوجد كلمات دلالية لهذا الموضوع ',
        'LNG_MY_TAGS' => 'كلماتي الدلالية',
        'LNG_TAGS_ADD' => 'أضف',
        'LNG_IN' => 'في',

        'LNG_SHARE_ON_SOCIAL_BOOKMARKS' => 'مشاركة في',

        'LNG_SUBMIT_BUTTON' => 'أرسل',
        'LNG_RESET_BUTTON' => 'إستعادة',
        'LNG_VOTES_BUTTON' => 'صوت',
        'LNG_MAIL_BUTTON' => 'إشترك',
        'LNG_SEARCH_BUTTON' => 'بحث',
        'LNG_ADD_COMMENTS_BUTTON' => 'أرسل',
        'LNG_CANCEL' => 'Cancel',

        'LNG_PLUGIN_CONTACT' => 'اتصل بنا',
        'LNG_PLUGIN_SITEMAP' => 'مخطط الموقع',

        'LNG_AUTHORS' => 'المؤلفين',
        'LNG_AUTHOR_BY' => 'بواسطة',
        'LNG_AUTHOR_INFO' => 'معلومات المؤلف',
        'LNG_AUTHOR_LINK' => 'مقدم بواسطة',
        'LNG_FEATURED_AUTHOR' => 'الكاتب المميز',

        'LNG_USER_FULL_NAME' => 'الاسم الكامل',
        'LNG_USER_FIRSTNAME' => 'الاسم الأول',
        'LNG_USER_SECONDNAME' => 'الكنية',

        'LNG_USER_AUTHOR' => 'المؤلف',
        'LNG_USER_EMAIL' => 'البريد الإلكتروني',
        'LNG_USER_INTEREST' => 'نقطة الإهتمام:',
        'LNG_USER_FEED' => 'تغذية المؤلف',
        'LNG_USER_PICTURE' => 'صورة',
        'LNG_USER_PUBLISHED' => 'المقالات المنشورة:',
        'LNG_USER_TEXT' => 'موجز السيرة الذاتية',
        'LNG_USER_WWW' => 'الموقع',

        'LNG_USER_ADD' => 'إضافة مستخدم:',
        'LNG_USER_ADDED' => 'أضيف العضو الجديد بنجاح',
        'LNG_USER_ALREADY_EXIST' => 'اسم المستخدم موجود بالفعل',

        'LNG_USER_USERNAME' => 'اسم المستخدم',
        'LNG_USER_PASSWORD' => 'كلمة المرور',
        'LNG_USER_FORGOT_YOUR_PASSWORD' => 'نسيت كلمة المرور؟',
        'LNG_USER_FIRSTNAME' => 'الاسم الأول',
        'LNG_USER_FIRST_NAME' => 'الاسم الأول',
        'LNG_USER_LAST_NAME' => 'الكنية',

        'LNG_USER_LOGIN' => 'تسجيل دخول',
        'LNG_USER_LOGOUT' => 'تسجيل خروج',
        'LNG_USER_REMEMBER_ME' => 'تذكر بياناتي',
        'LNG_USER_EMPTY' => 'اسم المستخدم لا يمكن أن يكون فارغاً',
        'LNG_USER_SUBMIT' => 'إضافة مستخدم',

        'LNG_USER_UPLOAD' => 'الملف صحيح, ورفع بنجاح.',
        'LNG_USER_UPLOAD_ERROR' => 'إحتمال الملف المرفوع مهاجم!',

        'LNG_ADMIN' => 'الإدارة',
        'LNG_USER_GROUP_0' => 'الكاتب',
        'LNG_USER_GROUP_1' => 'المحرر',
        'LNG_USER_GROUP_2' => 'الإدارة',
        'LNG_USER_GROUP_3' => 'الكاتب الموثوق',
        'LNG_USER_GROUP_4' => 'العضو',
        'LNG_USER_GROUP_5' => 'العضو المميز',

        'LNG_RELATED_LINKS' => 'لا يوجد أخبار مماثلة لهذا المقال',
        'LNG_RELATED_LINK_BY' => 'بواسطة',
        'LNG_RELATED_LINK_POST' => 'أرسل في',

        'LNG_VOTES' => 'التصويتات',
        'LNG_VOTES_TOTAL' => 'المجموع',
        'LNG_VOTES_RATING' => 'التقييم:',
        'LNG_RATE_ARTICLE' => 'قيم هذا المقال',
        'LNG_VOTES_SCRIPT_OK' => 'شكرا لتصويتك لهذا المقال.',
        'LNG_VOTES_SCRIPT_ALREADY' => 'لقد صوت من قبل لهذا المقال!',

        'LNG_MOST_POPULAR' => 'الأكثر شعبية',
        'LNG_MOST_EMAILED' => 'الأكثر إرسالاً',
        'LNG_MOST_COMMENTED' => 'الأكثر تعليقاً',
        'LNG_TOP_RATED' => 'الأعلى تقييماً',

        'LNG_ALL_NEWS' => 'كل الأخبار',
        'LNG_MORE_NEWS' => 'المزيد من الأخبار',
        'LNG_MORE_FROM' => 'المزيد في',
        'LNG_RELATED_NEWS' => 'أخبار ذات صلة',
        'LNG_FEATURED_NEWS' => 'العناوين',
        'LNG_LATEST_NEWS' => 'أخر الإضافات',

        'LNG_BACK' => 'خلف',
        'LNG_PAUSE' => 'توقف',
        'LNG_FORWARD' => 'أمام',

        'LNG_SU' => 'أح',
        'LNG_MO' => 'إث',
        'LNG_TU' => 'ثلا',
        'LNG_WE' => 'أر',
        'LNG_TH' => 'خم',
        'LNG_FR' => 'جم',
        'LNG_SA' => 'سبت',
        'LNG_MONTH_1' => 'كانون الثاني',
        'LNG_MONTH_2' => 'شباط',
        'LNG_MONTH_3' => 'أذار',
        'LNG_MONTH_4' => 'نيسان',
        'LNG_MONTH_5' => 'أيار',
        'LNG_MONTH_6' => 'حزيران',
        'LNG_MONTH_7' => 'تموز',
        'LNG_MONTH_8' => 'آب',
        'LNG_MONTH_9' => 'أيلول',
        'LNG_MONTH_10' => 'تشرين الأول',
        'LNG_MONTH_11' => 'تشرين الثاني',
        'LNG_MONTH_12' => 'كانون الأول',
        'LNG_MONTH_SHORT_1' => 'ك 2',
        'LNG_MONTH_SHORT_2' => 'شباط',
        'LNG_MONTH_SHORT_3' => 'أذار',
        'LNG_MONTH_SHORT_4' => 'نيسان',
        'LNG_MONTH_SHORT_5' => 'أيار',
        'LNG_MONTH_SHORT_6' => 'حزيران',
        'LNG_MONTH_SHORT_7' => 'تموز',
        'LNG_MONTH_SHORT_8' => 'آب',
        'LNG_MONTH_SHORT_9' => 'أيلول',
        'LNG_MONTH_SHORT_10' => 'ت 1',
        'LNG_MONTH_SHORT_11' => 'ت 2',
        'LNG_MONTH_SHORT_12' => 'ك 1',

        'LNG_CODE' => 'الكود',

        'LNG_TO' => 'إلى',
        'LNG_BCC' => 'نسخة إلى',
        'LNG_MESSAGE' => 'الرسالة',
        'LNG_YOUR_EMAIL_ADDRESS' => 'بريدك الإلكتروني',
        'LNG_CONFIRM_PASSWORD' => 'تأكيد كلمة المرور',
        'LNG_EMAIL_FRIEND' => 'أرسل إلى صديق',

        'LNG_SIGN_UP' => 'تسجيل',
        'LNG_ENETER_YOUR_NEW_PASSWORD' => 'أدخل كلمة المرور الجديدة',


        'LNG_MAIL_ADDRESS' => 'البريد الإلكتروني',
        'LNG_SENDEMAIL_SUBMIT' => 'أرسل',

        'LNG_MORE_HEADLINES' => 'عناوين أخبار أخرى',
        'LNG_HEADLINE_LINK' => 'تفاصيل أكثر',
        'LNG_FULL_STORY' => ' تفاصيل أكثر ',
        'LNG_VISIT_WEBSITE' => ' زيارة الموقع ',
        'LNG_DOWNLOAD_ATTACHMENT' => 'تحميل المرفق',
        'LNG_ATTACHMENTS' => 'المرفقات',
        'LNG_CLICK_ACCESS_LINK' => 'إضغط على التالي للوصول إلى وصلة الإرسال',

        'LNG_RESTRICTED_ACCESS' => 'الوصول مقيد.',
        'LNG_RESTRICTED_ONLY_REGISTERED' => 'فقط الأعضاء المسجلين بإمكانهم مشاهدة هذا المقال.',
        'LNG_RESTRICTED_ONLY_PREMIUM' => 'فقط الأعضاء المميزين بإمكانهم مشاهدة هذا المقال.',

        'LNG_IMAGE' => 'الصورة',
        'LNG_INCORRECT_CAPTCHA' => 'كود الصورة غير صحيح.',

        'LNG_TAG' => 'كلمة بحث',
        'LNG_TAGS' => 'كلمات دلالية',

        'LNG_ARCHIVE' => 'الأرشيف',
        'LNG_ARCHIVE_INCLUDE' => 'يتضمن الأرشيف',
        'LNG_ARCHIVE_NAVIGATE' => 'تصفح الأرشيف',
        'LNG_ARCHIVE_SEARCH' => 'بحث في الأرشيف',

        'LNG_ADD_FAVORITES' => 'أضفنا إلى المفضلة',
        'LNG_PRINT_VERSION' => 'نسخة للطباعة',

        'LNG_GO'=> 'إذهب',
        'LNG_GO_HOME' => 'الرئيسية',
        'LNG_SET_HOMEPAGE' => 'إجعلنا صفحتك الرئيسية',
        'LNG_SITEMAP' => 'خريطة الموقع',
        'LNG_SECTIONS' => 'أقسام الموقع',
        'LNG_PLAIN_TEXT' => 'نص بسيط',
        'LNG_SITE_ADMINISTRATION' => 'إدارة الموقع',
        'LNG_CLOSE' => 'إغلاق',
        'LNG_DISPLAYING' => 'عرض',
        'LNG_TOTAL' => 'المجموع',
        'LNG_PAGE_NOT_FOUND' => 'لا يمكن العثور على الصفحة',
        'LNG_FONT_SIZE' => 'حجم الخط:',
        'LNG_TIMES_READ' => 'عدد القراءات',

//Register
        'LNG_EDIT_PERSONAL_INFORMATION' => 'تعديل المعلومات الشخصية',
        'LNG_SAVE' => 'حفظ',
        'LNG_EMAIL_TAKEN' => 'البريد الإلكتروني غير متاح.',
        'LNG_CHECKING_EMAIL_AVAILABILITY' => 'التحقق من وجود البريد الإلكتروني ...',
        'LNG_YOUR_WEBSITE_MUST_BE_A_VALID_URL' => 'رابط الموقع يجب أن يكون صحيحاً.',
        'LNG_EMAIL_ADDRESS_VALID' => 'البريد الإلكتروني صحيح.',
        'LNG_EMAIL_ADDRESS_NOT_VALID' => 'البريد الإلكتروني غير صحيح.',
        'LNG_VERY_WEAK' => 'ضعيف جداً',
        'LNG_WEAK' => 'ضعيف',
        'LNG_GOOD' => 'جيد',
        'LNG_STRONG' => 'قوي',
        'LNG_VERY_STRONG' => 'قوي جداً',
        'LNG_PASSWORD_TOO_SHORT' => 'كلمة المرور قصيرة جداً. الحد الأدنى هو 6 أحرف.',
        'LNG_PASSWORD_MUST_NOT_CONTAIN_USERNAME' => 'كلمة المرور يجب أن لا تحتوي اسم المستخدم.',
        'LNG_TOO_MANY_REPEATED_CHARACTERS' => 'شخصيات متكررة جداً.',
        'LNG_PASSWORD_INVALID' => 'كلمة المرور غير صحيحة.',
        'LNG_PASSWORDS_ARE_NOT_IDENTICAL' => 'كلمة المرور غير متطابقة.',
        'LNG_PASSWORDS_ARE_IDENTICAL' => 'كلمة المرور متطابقة.',
        'LNG_CHECKING_USERNAME_AVAILABILITY' => 'التحقق من إتاحة كلمةالمرور...',
        'LNG_USERNAME_TAKEN' => 'اتخدت اسم المستخدم',
        'LNG_USERNAME_AVAILABLE' => 'اسم المستخدم متاح.',
        'LNG_COULD_NOT_CHECK_AVAILABILITY' => 'لا يمكن التحقق من التوافر في هذا الوقت.',
        'LNG_USERNAME_TOO_SHORT' => 'اسم الستخدم قصير جداً!',
        'LNG_USERNAME_INVALID' => 'اسم المستخدم غير صحيح!',
        'LNG_USERNAME_VALID' => 'اسم المستخدم صالح.',
        'LNG_REGISTER_VALID_URL' => 'الرابط صالح.',
        'LNG_REGISTER_INVALID_URL' => 'الرابط غير صالح.',
        'LNG_USERNAME_NOT_VALID' => 'اسم المستخدم غير صالح',
        'LNG_IS_ALREADY_TAKEN' => 'مستخدم بالفعل',
        'LNG_YOU_HAVE_TO_ENTER_IDENTICAL_PASSWORD' => 'يجب إدخال كلمة مرور متطابقة في كل الخانات!',
        'LNG_YOU_HAVE_TO_TYPE_IN_A_REAL_EMAIL' => 'يجب عليك استخدام بريد إلكتروني صحيح!',
        'LNG_TERMS_OD_SERVICE_INFO' => 'يجب عليك أن تتأكد من أنك قرأت ووافقت على الشروط.',
        'LNG_FORGOT_YOUR_PASSWORD' => 'نسيت كلمة المرور?',
        'LNG_RETURN_TO_LOGIN' => 'العودة إلى تسجيل الدخول',
        'LNG_USER_TOS_REGISTER' => 'بتسجيلك أنت توافق على',
        'LNG_USER_TOS' => 'شروط الخدمة',
        'LNG_REGISTRATION_CLOSED' => 'التسجيل في الموقع مغلق حالياً.',


        //Close site
        'LNG_SITE_CLOSED' => 'الموقع مغلق حالياً.',
        'LNG_SITE_CLOSED_REASON' => 'سبب الإغلاق',
        'LNG_SITE_CLOSED_VISIT_LATER' => 'من فضلك, أعد الزيارة لاحقاً',

        //404 page not found
        'LNG_404_NOT_FOUND' => 'لم يتم العثور على الصفحة',
        'LNG_404_NOT_FOUND_INFO' => 'الرابط المطلوب لم يتم العثور عليه في هذا الخادم.',
        'LNG_404_NOT_FOUND_NOTIFY' => 'إذا كنت تعتقد أن هذه الصفحة ينبغي أن تكون هنا. من فضلك',
        'LNG_404_NOT_FOUND_NOTIFY_LINK' => 'أعلم مدير الموقع.',
        'LNG_404_GO_HOME' => 'الذهاب للصفحة الرئيسية',
        'LNG_INFO_REPORTED_404_SUCCESS' => 'شكراً لتبليغك عن الرابط المفقود.',
        'LNG_REPORT_404_MAIL_SUBJECT' => 'الخطأ 404 من الرابط <WEBSITE_TITLE>',
        'LNG_REPORT_404_BODY' => 'أحدهم أبلغ عن الخطأ 404 بعدم العثور على الصفحة.',

        //Admin meny
        'LNG_EDIT_ARTICLE_OPTION' => 'خيارات تعديل المقال',
        'LNG_EDIT_CATEGORY_OPTION' => 'خيارات تعديل القسم',
        'LNG_MODERATE_COMMENTS' => 'مراقبة التعليقات',

        //FRON-END SERVICE INFO

        'LNG_INFO_FORGOT_PASSWORD_INFO' => 'الرجاء أدخل اسم المستخدم أو عنوان البريد الإلكتروني الذي قدم خلال التسجيل. اذا كان اسم المستخدم أو عنوان البريد الإلكتروني موجود لدينا، سوف تتلقى تعليمات لإستعادة كلمة السر.',
        'LNG_INFO_FORGOT_PASSWORD_NOTICE' => 'يجب أن تتلقى التعليمات لإستعادة كلمة السر قريباً.',
        'LNG_INFO_FORGOT_PASSWORD__HAS_BEEN_SUCCESSFULLY_CHANGED' => 'تم تغيير كلمة المرور بنجاح.',

        //Articles action
        'LNG_INFO_ARTICLE_VOTE_SUCCESS' => 'شكرا لتصويتك.',
        'LNG_INFO_ARTICLE_E_MAIL_TO_A_FRIEND_SENT_SUCCESS' => 'البريد الإلكتروني لـ <MAIL_TO> أرسل بنجاح.',

        //Comments action
        'LNG_INFO_COMMENT_ADD_SUCCESS' => 'تم إضافة تعليقك.',
        'LNG_INFO_COMMENT_REPORTING_SUCCESS' => 'تعليقات غير لائقة.',
        'LNG_INFO_COMMENT_VOTE_SUCCESS' => 'تم التصويت بنجاح',

        'LNG_INFO_USER_REGISTER_SUCCESS' => '<strong>تم بنجاح. نشكرك على التسجيل في موقعنا!</strong><br /><br />يمكنك الأن الإستفادة من الميزات المتقدمة من موقعنا. في غضون الدقائق القليلة المقبلة، أنت ستتلقى التأكيد بالبريد الإلكتروني. لتنشيط حسابك يجب عليك النقر على الوصلة التي ستصلك في رسالة البريد الألكتروني.<br /><br /><em>من فضلك إنتبه:</em> إذا لم تجد رسالة التأكيد في البريد الالكتروني في صندوق الوارد، يرجى النظر في "junk mail" أو صندوق المحذوفات فربما ترسل بالخطأ.',
        'LNG_INFO_USER_CONFIRM_SUCCESS' => 'تسجيلك إكتمل بنجاح',
        'LNG_THANK_YOU_FOR_CONFIRMING' => 'You have successfully completed registration process.',
        'LNG_INFO_USER_EDIT_SUCCESS' => 'ملف المستخدم تم تعديله بنجاح',

        'LNG_REGISTRATION_SUBJECT' => 'التسجيل',
        'LNG_CONFIRMATION_EMAIL' => 'عزيزي <FULLNAME>,<br />نشكرك على الإشتراك! أنقر على الرابط التالي أو انسخ وألصق هذا الرابط إلى المتصفح لتنشيط حسابك:<br /><br /><ACTIVATION_URL><br /><br />الرجاء الملاحظة إن هذا كود التفعيل وليس كلمة السر الخاصة بك.<br /><br />شكرا لإستخدامك خدماتنا<br /><br />مع أطيب التحيات,<br /><WEBSITE_NAME><br /><WEBSITE_URL>',

        'LNG_NO_ENTRIES' => 'لا يوجد أي إدخالات تتوافق مع المعايير الخاصة بك.',
        'LNG_ALLERADY_LOGGED_IN' => 'تم تسجيل الدخول بالفعل',

        //Blog section
        'LNG_POPULAR_POSTS' => 'المقالات الأكثر شعبية',
        'LNG_BLOGGERS' => 'المدونون',
        'LNG_AUTHORS_BLOGS' => 'الكاتب/ المدونات',

        'LNG_PRETTY_DATE_PREFIX' => '',
        'LNG_PRETTY_DATE_SUFFIX' => ' مضت',
        'LNG_PRETTY_DATE_FEW_MOMENTS' => 'بضع دقائق',
        'LNG_PRETTY_DATE_VERY_LONG_TIME' => 'وقت طويل جداً',
        'LNG_PRETTY_DATE_1_MINUTE' => 'دقيقة واحدة',
        'LNG_PRETTY_DATE_MINUTES' => 'دقيقة',
        'LNG_PRETTY_DATE_1_HOUR' => 'ساعة واحدة',
        'LNG_PRETTY_DATE_HOURS' => 'ساعات',



        //FRONT-END SERVICE ERRORS

        'LNG_ERROR_2032' => 'بريد إلكتروني خاطئ',
        'LNG_ERROR_2033' => 'غير قادر على تحديث المقال بعد ارسال البريد الإلكتروني',
        'LNG_ERROR_2034' => 'البريد الإلكتروني خاطئ - لـ',
        'LNG_ERROR_2035' => 'لم يتم العثور على المقال',
        'LNG_ERROR_2036' => 'فقط الأعضاء المسجلين يمكنهم إرسال البريد الإلكتروني',

        'LNG_ERROR_2201' => 'عنوان الـ IP الخاص بك ممنوع.',
        'LNG_ERROR_2202' => 'الحماية من الفيضانات.',
        'LNG_ERROR_2203' => 'لا يمكنك إدراج تعليق في قاعدة البيانات.',
        'LNG_ERROR_2204' => 'كود الصورة خاطئ.',
        'LNG_ERROR_2205' => 'يجب أن تكون مسجلا لإضافة التعليقات.',
        'LNG_ERROR_2206' => 'إرسال التعليقات غير مسموح.',
        'LNG_ERROR_2219' => 'هذا التعليق غير وجود.',
        'LNG_ERROR_2220' => 'يجب تسجيل الدخول لإرسال تقرير.',
        'LNG_ERROR_2221' => 'من فضلك أدخل تعليقك.',
        'LNG_ERROR_2222' => 'أنت فعلاً قمت بالتصويت على هذا التعليق.',
        'LNG_ERROR_2223' => 'لا يمكنك التصويت على التعليق.',
        'LNG_ERROR_2224' => 'لا يمكنك التصويت على التعليق. من فضلك حاول لاحقاً',
        'LNG_ERROR_2225' => 'لا يوجد تعليق.',
        'LNG_ERROR_2226' => 'يتوجب عليك تسجيل الدخول لتقوم بالتصويت.',

        'LNG_ERROR_2314' => 'الحد الأدنى لكلمة المرور هو 6 أحرف.',
        'LNG_ERROR_2315' => 'كلمة المرور غير متطابقة.',
        'LNG_ERROR_2316' => 'خطأ في البريد الإلكتروني.',
        'LNG_ERROR_2317' => 'لا يمكنك تحديث المستخدم بعد حذف الصورة القديمة.',
        'LNG_ERROR_2318' => 'لا يمكنك تحديث المستخدم.',
        'LNG_ERROR_2319' => 'المستخدم غير صحيح.',
        'LNG_ERROR_2320' => 'الحد الأدنى لكلمة المرور هو 6 أحرف.',
        'LNG_ERROR_2321' => 'كلمة المرور غير متطابقة.',
        'LNG_ERROR_2322' => 'خطأ في البريد الإلكتروني.',
        'LNG_ERROR_2323' => 'لا يمكنك تحديث المستخدم بعد حذف الصورة القديمة.',
        'LNG_ERROR_2324' => 'لا يمكنك تحديث المستخدم.',
        'LNG_ERROR_2325' => 'المستخدم غير صحيح.',
        'LNG_ERROR_2326' => 'لا يمكنك تعديل أسماء مستخدمين الأخرين.',
        'LNG_ERROR_2327' => 'ليس لديك صلاحيات لتعديل اسم المستخدم.',
        'LNG_ERROR_2328' => 'يتوجب عليك تسجيل دخول كي تتمكن من تعديل المستخدم.',

        'LNG_ERROR_2701' => 'اسم المستخدم موجود بالفعل.',
        'LNG_ERROR_2702' => 'عنوان الالبريد الإكتروني غير صحيح.',
        'LNG_ERROR_2703' => 'عنوان البريد الإكتروني موجود بالفعل.',
        'LNG_ERROR_2704' => 'اسم المستخدم غير صحيح.',
        'LNG_ERROR_2705' => 'اسم المستخدم موجود بالفعل.',
        'LNG_ERROR_2706' => 'كلمة السر يجب أن تتضمن الحد الأدنى 6 حروف.',
        'LNG_ERROR_2707' => 'كلمة السر غير مطابقة.',
        'LNG_ERROR_2708' => 'لا يمكنك إضافة المستخدم في قاعدة البيانات.',
        'LNG_ERROR_2709' => 'لا يمكنك التسجيل لأنك قد سجلت الدخول بالفعل.',
        'LNG_ERROR_2710' => 'بيانات التأكيد غير صحيحة.',
        'LNG_ERROR_2711' => 'لا يمكنك تأكيد ملفك الشخصي.',
        'LNG_ERROR_2712' => 'يجب أن تحدد إما اسم المستخدم أو عنوان البريد الإلكتروني.',
        'LNG_ERROR_2713' => 'كود تنشيط العضوية غير صحيح.',
        'LNG_ERROR_2714' => 'كود التحقق غير صحيح.',
        'LNG_ERROR_2751' => 'اسم المستخدم أو كلمة السر غير صحيح. لقد استخدمت ثلاث محاولات المتاحة لك لتسجيل الدخول. عليك الآن الإنتظار ساعة قبل أن تتمكن من المحاولة مرة أخرى.',
        'LNG_ERROR_2752' => 'اسم المستخدم أو كلمة السر غير صحيح. بقي لك محاولة واحدة لتسجيل الدخول.',
        'LNG_ERROR_2753' => 'اسم المستخدم أو كلمة السر غير صحيح. بقي لك محاولتان لتسجيل الدخول.',
        'LNG_ERROR_2754' => 'أنت عضو غير نشط.',
        'LNG_ERROR_2755' => 'لقد سبق وأن أرسلت طلب `فقدان البريد`.',
        'LNG_ERROR_2756' => 'تعليقك يجب أن يتضمن أكثر من 30 حرفا ولا يتجاوز 1000 حرف',
        'LNG_PLUGIN_IMAGE_GALLERY_BOX_TITLE' => 'معرض الصور',
        'LNG_PLUGIN_IMAGE_GALLERY_NEXT' => 'التالي',
        'LNG_PLUGIN_IMAGE_GALLERY_PREV' => 'السابق',
        //Article service
        'LNG_ERROR_2001' => 'وصف التقرب من محركات البحث موجود سابقاً.',
        'LNG_ERROR_2002' => 'لا يمكنك إدراج مقال في قاعدة البيانات',
        'LNG_ERROR_2003' => 'لا تملك إمتيازات كافية لإضافة مقال جديد.',
        'LNG_ERROR_2004' => 'يجب أن تكون مسجلا لإضافة المقالات.',
        'LNG_ERROR_2005' => 'لا يمكنك حذف المقالات المختارة.',
        'LNG_ERROR_2006' => 'لا يمكنك حذف المقالات المختارة (حذف كتلة).',
        'LNG_ERROR_2007' => 'لا يمكنك حذف المقالات المختارة.',
        'LNG_ERROR_2008' => 'لا تملك إمتيازات كافية لحذف المقالات.',
        'LNG_ERROR_2009' => 'يجب تسجيل الدخول لحذف المقالات.',
        'LNG_ERROR_2010' => 'لا يمكنك تحديد الجداول (إختيار واسع).',
        'LNG_ERROR_2011' => 'لا يمكنك تحديد الجداول.',
        'LNG_ERROR_2012' => 'لا تملك إمتيازات كافية لتشغيل خيارات المقال.',
        'LNG_ERROR_2013' => 'يجب تسجيل الدخول لتشغيل خيارات المقال.',
        'LNG_ERROR_2014' => 'وصف التقرب من محركات البحث موجود سابقاً.',
        'LNG_ERROR_2015' => 'لا يمكنك تحديث المقال.',
        'LNG_ERROR_2016' => 'لم يتم العثور على المقال.',
        'LNG_ERROR_2017' => 'لا تملك إمتيازات كافية لتحرير المقال.',
        'LNG_ERROR_2018' => 'يجب تسجيل الدخول لتحرير المقالات',
        'LNG_ERROR_2019' => 'لا يمكنك إعادة ترتيب المقال',
        'LNG_ERROR_2020' => 'لا تملك إمتيازات كافية لإعادة ترتيب المقالات.',
        'LNG_ERROR_2021' => 'يجب تسجيل الدخول لإعادة ترتيب المقالات.',
        'LNG_ERROR_2022' => 'لا يمكنك تحديث المقال بعد حذف الصورة القديمة.',
        'LNG_ERROR_2023' => 'لم يتم العثور على المقال.',
        'LNG_ERROR_2024' => 'لا تملك إمتيازات كافية لحذف صورة المقال.',
        'LNG_ERROR_2025' => 'يجب تسجيل الدخول لحذف صورة المقال.',
        'LNG_ERROR_2026' => 'لا يمكنك تحديث المقال بعد حذف الملف المرفق.',
        'LNG_ERROR_2027' => 'لم يتم العثور على المقال.',
        'LNG_ERROR_2028' => 'لا تملك إمتيازات كافية لحذف الملف المرفق.',
        'LNG_ERROR_2029' => 'يجب تسجيل الدخول لحذف الملف المرفق.',
        'LNG_ERROR_2030' => 'لا يمكنك تحديث المقال - تصويت.',
        'LNG_ERROR_2031' => 'لم يتم العثور على المقال.',
        'LNG_ERROR_2037' => 'اسم SE موجود بالفعل. قم بإفراغ سلة المحذوفات أو اختر اسم أخرى.',
    )
]
?>
